apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tradingtools.configmapName" . }}
  labels:
    {{- include "tradingtools.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.config | nindent 2 }}
