image:
  tag: "dev-ae06538"
namespace:
  name: "tradingtool-dev"
  create: true
config:
  LOG_LEVEL: "debug"
  AUTH_ENABLED: "true"
  KEYCLOAK_URL: "https://keycloak-dev.liontechsolution.com"
  KEYCLOAK_REALM: "tradingtool-dev"
  KEYCLOAK_AUDIENCE: "tradingtool-api"
  KEYCLOAK_FRONTEND_CLIENT_ID: "tradingtool-web"
  CORS_ORIGINS: "*"
existingSecret: "tradingtools-secret-dev"
cloudflareTunnel:
  enabled: true
  existingSecret: "tradingtools-secret-dev"
networkPolicy:
  # Enable egress NetworkPolicy to allow traffic to the PostgreSQL namespace
  enabled: true
  # Namespace where PostgreSQL is deployed
  postgresNamespace: "data-dev"
