image:
  tag: "dev-bd42153"
namespace:
  name: "tradingtool-dev"
  create: true
config:
  LOG_LEVEL: "debug"
  AUTH_ENABLED: "true"
  CORS_ORIGINS: "*"
existingSecret: "tradingtools-secret-dev"
cloudflareTunnel:
  enabled: true
  existingSecret: "tradingtools-secret-dev"
networkPolicy:
  # Enable egress NetworkPolicy to allow traffic to the PostgreSQL namespace
  enabled: true
  # Namespace where PostgreSQL is deployed
  postgresNamespace: "data-dev"
